In [1]:
import pandas as pd

In [9]:
price_df = pd.read_csv("../data/raw/pricePerProvince.csv", encoding='latin1')
price_df

                   province  price per ¢/kWh
0                   Alberta             25.8
1          British Columbia             11.4
2                  Manitoba             10.2
3             New Brunswick             13.9
4   Newfoundland & Labrador             14.8
5               Nova Scotia             18.3
6     Northwest Territories             41.0
7                   Nunavut             35.4
8                   Ontario             14.1
9      Prince Edward Island             18.4
10                   Quebec              7.8
11             Saskatchewan             19.9
12          Yukon Territory             18.7

In [7]:
price_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   province         13 non-null     object
 1   price per ¢/kWh  13 non-null     float64
dtypes: float64(1), object(1)
memory usage: 340.0+ bytes

In [36]:
sunlight_df = pd.read_csv("../data/raw/municip_kWh.csv", encoding='latin1', skiprows=[0, 1, 2, 4], skipfooter=2)
sunlight_df = sunlight_df.rename(columns={'Mois': 'Month'})
sunlight_df['Province'] = sunlight_df['Province'].str.split('/').str[0]
sunlight_df['Month'] = sunlight_df['Month'].str.split('/').str[0]
sunlight_df.to_csv("../data/processed/processed_municip_kWh.csv")
sunlight_df

C:\Users\Marcony1\AppData\Local\Temp\ipykernel_2104\2479432145.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support skipfooter; you can avoid this warning by specifying engine='python'.
  sunlight_df = pd.read_csv("../data/raw/municip_kWh.csv", encoding='latin1', skiprows=[0, 1, 2, 4], skipfooter=2)

,Province,Municipality,Month,South-facing with vertical (90 degrees) tilt,South-facing with latitude tilt,South-facing with tilt=latitude+15 degrees,South-facing with tilt=latitude-15 degrees,2-axis tracking,Horizontal (0 degree)
0,Alberta,Acadia Valley,January,3.78,3.57,3.83,3.11,4.31,1.23
1,Alberta,Acadia Valley,February,4.69,4.78,4.96,4.35,5.87,2.23
2,Alberta,Acadia Valley,March,4.79,5.58,5.49,5.37,7.20,3.63
3,Alberta,Acadia Valley,April,4.09,5.80,5.34,5.96,8.43,4.96
4,Alberta,Acadia Valley,May,3.37,5.59,4.88,6.06,9.06,5.84
...,...,...,...,...,...,...,...,...,...
45573,Yukon Territory,Whitehorse,September,3.00,3.68,3.45,3.69,4.86,2.61
45574,Yukon Territory,Whitehorse,October,2.10,2.29,2.27,2.19,2.76,1.20
45575,Yukon Territory,Whitehorse,November,1.33,1.31,1.36,1.18,1.49,0.44
45576,Yukon Territory,Whitehorse,December,0.74,0.70,0.74,0.62,0.78,0.19
45577,Yukon Territory,Whitehorse,Annual,2.83,3.51,3.24,3.60,5.02,2.77

In [35]:
sunlight_df[["Province", "Municipality"]].value_counts()

Province         Municipality
Alberta          Acadia Valley                         13
Ontario          Spencerville                          13
                 Smithville                            13
                 Smooth Rock Falls                     13
                 Sombra                                13
                                                       ..
New Brunswick    Saint-Isidore                         13
                 Saint-Jean-Baptiste-de-Restigouche    13
                 Saint-Louis de Kent                   13
                 Saint-LÃ©olin                         13
Yukon Territory  Whitehorse                            13
Name: count, Length: 3506, dtype: int64